version: '3'

services:
  angular:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
    command: ng serve
  express:
    build: .
    volumes:
      - .:/usr/src/app/server
      - /usr/src/app/server/node_modules
    ports:
      - 3000:3000
    command: npm start