version: '3'

services:
  angularapp-service:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 4200:4200
    command: npm run serve